# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#

development:
  adapter: postgresql
  database: postgres
  pool: 5 
  timeout: 5000
  username: postgres
  password: scoala1989
  

 # On Heroku and other platform providers, you may have a full connection URL
 # available as an environment variable. For example:
 #
DATABASE_URL="postgres://rkvckjdgeflzut:UEZ7PTjBWd9unZK7l_oK4YYMSc@ec2-46-137-72-123.eu-west-1.compute.amazonaws.com:5432/dbfe89ed8ohp20"
 #
 # You can use this database configuration with:
 #
production:
  url: <%= ENV['DATABASE_URL'] %>  